### ISSUE TITLE
能兼容下后台php的时间戳（10位）转日期格式

### ISSUE THREAD

**Issue by phpyii** [x-extends/xe-utils#14]
**（必填）这个需求解决了什么问题：**
解决后台不用转换一遍时间戳（10位转13位）

**建议的 API 是什么样的：**
日期格式化

**是否已有其他不错的替代方案：**
前端自己 *1000

**Comment by xuliangzhan** [comment]
没看出这种自身业务逻辑和工具库有什么关系？你写个方法统一转换不就行了

**Comment by phpyii** [comment]
是的，我在前端调用日期格式化方法又封装了一下 如果是10位转为13位。
