### ISSUE TITLE
Xe-utils的计算类方法用的toFixed有精度问题,。

### ISSUE THREAD

**Issue by adoin** [x-extends/xe-utils#17]
**（必填）请填写问题描述或截图：**
Xe-utils的计算类方法用的toFixed有精度问题,。比如XEUtils.commafy(4.555, { digits: 2 }) 得到的是4.55字符串 期望是4.56 但是很多地方又正常，根本原因是用的toFixed，这个依然有精度问题。
可以参考Lodash.round(val,pre)的计算方式通过十进制乘积（e）然后Math.round或者其他的精度换算方法。然后再格式化成三位一撇
**（必填）请填在线链接：**
https://codesandbox.io/s/fancy-feather-tgmo8?file=/src/components/HelloWorld.vue

**（必填）请填写期望的结果：**
4.56
**请填写以下信息：**

- OS: Win
- Browser: Chrome

**Comment by xuliangzhan** [comment]
建议更新到最新版本试下

**Comment by adoin** [comment]
嗯 发现修复了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x-extends/xe-utils"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月4日(星期二) 上午9:55
收件人:&nbsp;"x-extends/xe-utils"<xe-utils@noreply.github.com&gt;;
抄送:&nbsp;"adoin"<adoin@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [x-extends/xe-utils] Xe-utils的计算类方法用的toFixed有精度问题,。 (#17)





 
建议更新到最新版本试下
