### ISSUE TITLE
commafy函数格式化后，全部变整数，没有保留小数位

### ISSUE THREAD

**Issue by jianliulin** [x-extends/xe-utils#24]
**（必填）请填写问题描述或截图：**
commafy函数格式化后，全部变整数，没有保留小数位。

**（必填）请填在线链接：**
https://jsrun.net/iyLKp/edit
**（必填）请填写期望的结果：**
正确格式化

**请填写以下信息：**

- OS: windows server 2008 R2
- Browser: chrome

**Comment by xuliangzhan** [comment]
由于该参数 [commafy.fixed](https://x-extends.gitee.io/xe-utils/#/?to=commafy)  从 v2 开始已经不建议使用了，已经补充测试用例了，可以更新到 v2.8.1
https://jsrun.net/jS6Kp/edit

**Comment by jianliulin** [comment]
谢谢！！
