### ISSUE TITLE
npm下载包报错

### ISSUE THREAD

**Issue by 1109332657** [x-extends/xe-utils#25]
**（必填）请填写问题描述或截图：**
按官方的代码npm下载；
然后报错：
~~~
This dependency was not found:

* xe-utils/ctor in ./node_modules/_vxe-table@4.0.0-beta.1@vxe-table/lib/index.common.dev.js

To install it, you can run: npm install --save xe-utils/ctor
~~~
然后一直找不到文件
~~~
npm install --save xe-utils/ctor
info: please complete authentication in your browser...-session 8dac29d32b933405
npm ERR! Error while executing:
npm ERR! D:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/xe-utils/ctor.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\86137\AppData\Roaming\npm-cache\_logs\2020-12-03T09_24_01_251Z-debug.log
~~~

**Comment by xuliangzhan** [comment]
应该检查对应的版本号是否正确

**Comment by 1109332657** [comment]
我用最新的版本弄的
然后按这个贴说的旧的就可以
https://github.com/x-extends/vxe-table/issues/1176




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xuliangzhan"<notifications@github.com&gt;; 
发送时间: 2020年12月3日(星期四) 晚上6:20
收件人: "x-extends/xe-utils"<xe-utils@noreply.github.com&gt;; 
抄送: "1109332657"<1109332657@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [x-extends/xe-utils] npm下载包报错 (#25)





 
应该检查对应的版本号是否正确

**Comment by 1109332657** [comment]
npm i xe-utils@2.8.2 npm i vxe-table@2.9.18
这个可以，最新的xe-utils和最新的 vxe-table不可以

**Comment by xuliangzhan** [comment]
有问题应该说出具体版本号，而不是说最新，不然谁能知道什么时候的最新是最新

**Comment by 1109332657** [comment]
vue@2.6.10
~~~
npm install xe-utils vxe-table
npm WARN vxe-table@3.0.8 requires a peer of xe-utils@>= 3 but none is installed. You must install peer dependencies yourself.
npm WARN vue-admin-template@4.1.0 No repository field.
npm WARN The package autoprefixer is included as both a dev and production dependency.

+ xe-utils@1.9.8
+ vxe-table@3.0.8
removed 4 packages and updated 3 packages in 18.624s

44 packages are looking for funding
  run `npm fund` for details
~~~
~~~
cnpm run dev
process.env.NODE_ENV development
 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                      上午9:26:34

This dependency was not found:

* xe-utils/ctor in ./node_modules/vxe-table/lib/index.common.dev.js

To install it, you can run: npm install --save xe-utils/ctor
~~~

**Comment by 1109332657** [comment]
~~~
npm install xe-utils@3
npm WARN vue-element-extends@1.2.24 requires a peer of xe-utils@^1.8.26 but none is installed. You must install peer dependencies yourself.
npm WARN vue-admin-template@4.1.0 No repository field.
npm WARN The package autoprefixer is included as both a dev and production dependency.

+ xe-utils@3.0.3
removed 2 packages and updated 1 package in 13.582s

44 packages are looking for funding
  run `npm fund` for details
~~~
后面的npm run dev
可以了

**Comment by xuliangzhan** [comment]
> vue@2.6.10
> 
> ```
> npm install xe-utils vxe-table
> npm WARN vxe-table@3.0.8 requires a peer of xe-utils@>= 3 but none is installed. You must install peer dependencies yourself.
> npm WARN vue-admin-template@4.1.0 No repository field.
> npm WARN The package autoprefixer is included as both a dev and production dependency.
> 
> + xe-utils@1.9.8
> + vxe-table@3.0.8
> removed 4 packages and updated 3 packages in 18.624s
> 
> 44 packages are looking for funding
>   run `npm fund` for details
> ```
> 
> ```
> cnpm run dev
> process.env.NODE_ENV development
>  INFO  Starting development server...
> 98% after emitting CopyPlugin
> 
>  ERROR  Failed to compile with 1 errors                                                                      上午9:26:34
> 
> This dependency was not found:
> 
> * xe-utils/ctor in ./node_modules/vxe-table/lib/index.common.dev.js
> 
> To install it, you can run: npm install --save xe-utils/ctor
> ```

其实你要是认真看一下第二行的警告信息，说不定早就解决了😆

**Comment by 1109332657** [comment]
是的

**Comment by su123jin** [comment]
"vxe-table": "^2.9.13",
    "vxe-table-plugin-antd": "1.8.10",
    "xe-utils": "^2.4.8",
需要node版本14以下的，我用的12.22.12的版本可以，高版本的话就会报这个提示To install it, you can run: npm install --save xe-utils/ctor
