### ISSUE TITLE
d.ts文件扩展失败

### ISSUE THREAD

**Issue by SunRisingChang** [x-extends/xe-utils#29]
**（必填）请填写问题描述或截图：**
？
![image](https://user-images.githubusercontent.com/24834134/115560348-15b10580-a2e7-11eb-96ae-a81b0da6b72c.png)

**（必填）请填在线链接：**
？
![image](https://user-images.githubusercontent.com/24834134/115560014-c8349880-a2e6-11eb-87bd-f41fddb424d6.png)
![image](https://user-images.githubusercontent.com/24834134/115560062-d1256a00-a2e6-11eb-916f-17e63ee05b2c.png)

**（必填）请填写期望的结果：**
？MapTreeOptions、TerrResult、FindTreeOptions未进行导出导致扩展失败

**请填写以下信息：**

- OS: ？Windows10
- Browser: ？Chrome

**Comment by xuliangzhan** [comment]
这个是没有导出的，什么原因需要用到这个呢

**Comment by SunRisingChang** [comment]
![image](https://user-images.githubusercontent.com/24834134/115566854-367c5980-a2ed-11eb-9426-aa032aa2086b.png)
使用ts引入模块后再重新导出  打包成ES6时 发生错误

**Comment by SunRisingChang** [comment]
非常感谢！已正常编译
