### ISSUE TITLE
utils.get 或者 utils.has,对于嵌套数组获取的结果失败

### ISSUE THREAD

**Issue by hao3304** [x-extends/xe-utils#34]
**（必填）请填写问题描述或截图：**
utils.get 或者 utils.has,对于嵌套数组获取的结果失败。

**（必填）请填在线链接：**
const list = [ [ 1 ] ];   utils.get(list, '[0][0]') 结果是undfined;
![image](https://user-images.githubusercontent.com/7592389/141070030-91941935-5b46-4833-9fcc-1d7879c46eca.png)

**（必填）请填写期望的结果：**
期望能正常取到值

**请填写以下信息：**

- OS: Window10
- Browser: Chrome  95.0.4638.69

**Comment by xuliangzhan** [comment]
建议更新到最新版本试试
