### ISSUE TITLE
clone深拷贝时，对于class类型的数据，没有完全深拷贝，依然会有引用关系，导致修改之后影响源数据

### ISSUE THREAD

**Issue by wekerSnail** [x-extends/xe-utils#35]
### 可复现的链接：

https://codesandbox.io/s/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-qeyeq?file=/src/App.vue:649-653

### 问题描述与截图：

![image](https://user-images.githubusercontent.com/30314164/141736789-5ceb8ab4-78d5-41dc-89cd-09e48820b905.png)

### 期望的结果：

和lodash结果一致

**Comment by xuliangzhan** [comment]
可以更新到最新版本看看

**Comment by wekerSnail** [comment]
最新版本可行
