### ISSUE TITLE
开启keep-source后进行深度克隆时， 克隆构造函数实例(getCtorObject )会报错

### ISSUE THREAD

**Issue by korylee** [x-extends/xe-utils#37]
### 可复现的链接：

https://codesandbox.io/s/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-xy9ly?file=/src/views/Demo1.vue

### 问题描述与截图：

    "vxe-table": "^3.4.13",
    "xe-utils": "^3.5.1"
开启keep-source后进行深度克隆时， 克隆构造函数实例(getCtorObject )会报错
![image](https://user-images.githubusercontent.com/62596617/150464996-484e3c31-ce09-42e1-8401-c02aa7002755.png)

谢谢

**Comment by xuliangzhan** [comment]
fix 3.5.3+
