### ISSUE TITLE
四舍五入保留三位小数针对 4.0455 错误结果 4.045

### ISSUE THREAD

**Issue by aijikai1997** [x-extends/xe-utils#38]
### 可复现的链接：

https://codesandbox.io/s/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-jnu4c?file=/src/main.js

### 问题描述与截图：

![image](https://user-images.githubusercontent.com/25819035/150715112-08df37b3-4842-4ff0-aa86-5f377505608a.png)

### 期望的结果：

4.0455保留3位小数结果应为4.046

### 操作系统：

window10

### 浏览器版本：

版本 87.0.4280.88

**Comment by xuliangzhan** [comment]
建议更新到最新版本
