### ISSUE TITLE
vite 构建打包失败（'default' is not exported，MatchesSelector）

### ISSUE THREAD

**Issue by cuishunbiao** [x-extends/xe-utils#49]
### 可复现的链接：

无

### 问题描述与截图：

项目环境：
"vite": "^2.9.9",
"vue": "^3.2.25",
"@rollup/plugin-commonjs": "^24.0.1",

项目中引用方式：
import 'xe-utils'
import VXETable from 'vxe-table'
import 'vxe-table/lib/style.css'

app.use(router)
app.use(VXETable)
app.mount('#app')

报错提示：

'default' is not exported by node_modules/xe-utils/objectEach.js, imported by node_modules/xe-utils/clone.js
file: /Users/cuishunbiao/company/product4/dispatchsystem/node_modules/xe-utils/clone.js:2:7
1: var objectToString = require('./staticObjectToString')
2: 
    ^
3: var objectEach = require('./objectEach')
4: var arrayEach = require('./arrayEach')
error during build:
Error: 'default' is not exported by node_modules/xe-utils/objectEach.js, imported by node_modules/xe-utils/clone.js

猜测是 rollup 支持 commonjs 的原因，然后在 vite.config.js 引入了：
import commonjs from '@rollup/plugin-commonjs'

并修改了 plugins 
plugins: [
vue(),
commonjs(),
]

然后可以打包成功，但报错 Uncaught TypeError: Cannot read properties of undefined (reading 'webkitMatchesSelector')。

想知道引起这个问题的原因是什么？

### 操作系统：

Mac 12.1

### 浏览器版本：

chrome 111.0.5563.64

**Comment by chunge16** [comment]
官方啥时候 支持 es 模式啊。。。。
