### ISSUE TITLE
Tree便利那些方法是不是TS有问题啊？文档能不能出TS版本呢

### ISSUE THREAD

**Issue by adoin** [x-extends/xe-utils#59]
### 可复现的链接：

无

### 问题描述与截图：

官方TS声明：![image](https://github.com/x-extends/xe-utils/assets/20517172/a4fae9ec-e5a9-4b81-a94f-33703de14064)
这个C应该怎么定义？

setup TS环境没有this...
目前只能丢个any 并且返回值强转
![image](https://github.com/x-extends/xe-utils/assets/20517172/21ea914c-7c0a-4e72-a9b2-2b627ce1b197)
希望文档补齐一下TS的使用

**Comment by xlz26296** [comment]
不知道你为啥要去强制指定类型，TS类型本来就是自动推导的

```typescript
const tree1 = [
  { id: 1 },
  {
    id: 2,
    children: [
      { id: 20 }
    ]
  }, {
    id: 3,
    children: [
      { id: 30 }
    ]
  }
]
XEUtils.mapTree(tree1, item => {
  return {
    id: item.id * 2
  }
})
```

**Comment by adoin** [comment]
> 不知道你为啥要去强制指定类型，TS类型本来就是自动推导的
> 
> ```ts
> const tree1 = [
>   { id: 1 },
>   {
>     id: 2,
>     children: [
>       { id: 20 }
>     ]
>   }, {
>     id: 3,
>     children: [
>       { id: 30 }
>     ]
>   }
> ]
> XEUtils.mapTree(tree1, item => {
>   return {
>     id: item.id * 2
>   }
> })
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save

群里那个就是你吧。。
都说了，你的例子的源和结果是可以互等的，这里肯定是出现错误才会强制指定类型，看不懂中文吗？
```TS
interface IAPI {
  name: string;
  url: string;
  method: 'post' | 'get';
  params?: Record<string, string>;
}
interface RenderEntity {
  uid: string;
  field?: string;
  factory: Bundle | FormFactory | DataFactory;
  config: Recordable;
  children?: RenderEntity[];
}
const fakeApiData: IAPI[] = [
      {
        name: '接口日志',
        params: {
          traceId: 'traceId',
          apiModelName: 'apiModelName',
        },
        url: '/v1/operation/sys/aipLog/queryAipLogPage',
        method: 'post',
      },
      {
        name: '饼图',
        params: {},
        url: '/v1/operation/sys/aip/report/count/charts/pie',
        method: 'post',
      },
    ];
const res:RenderEntity[] = mapTree(
      fakeData,
      (entity: DesignData) =>
        ({
          ...entity,
          factory:
            formFactories.find((f) => f.type === entity.factory) ??
            layoutBundles.find((f) => f.type === entity.factory) ??
            dataFactories.find((f) => f.type === entity.factory),
        } ),
    );
```
这是不强制指定的代码，TS是报错的好吗？ 别再犟了。你这里不强制指定怎么过啊？

**Comment by adoin** [comment]
> 不知道你为啥要去强制指定类型，TS类型本来就是自动推导的
> 
> ```ts
> const tree1 = [
>   { id: 1 },
>   {
>     id: 2,
>     children: [
>       { id: 20 }
>     ]
>   }, {
>     id: 3,
>     children: [
>       { id: 30 }
>     ]
>   }
> ]
> XEUtils.mapTree(tree1, item => {
>   return {
>     id: item.id * 2
>   }
> })
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save

因为报错了啊。但是其实是vcs的锅
